version: '3.3'
services:
  notification-cneter:
    build: .
    depends_on:
      - 'mongo'
      - 'rabbitmq'
  mongo:
    image: 'mongo:4.2.0'
    container_name: 'mongo'
    ports:
      - '27100:27017'
  rabbitmq:
    image: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'