version: '3.3'
services:
  notification-cneter:
    build: .
    restart: on-failure
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq
      - NOTIFICATION_REQUEST_QUEUE_NAME=notification_requests
      - SMS_QUEUE_NAME=sms_processed_notifications
      - PN_QUEUE_NAME=pn_processed_notifications
      - QUEUES_MAX_PRIORITY=10
      - NUMBER_OF_FRONT_LINE_CONSUMERS=2
      - NUMBER_OF_SMS_COMMUNICATORS=2
      - NUMBER_OF_PN_COMMUNICATORS=2
      - NUMBER_OF_SENDER_SIMULATOR=2
    depends_on:
      # - 'mongo'
      - 'rabbitmq'
  # mongo:
  #   image: 'mongo:4.2.0'
  #   container_name: 'mongo'
  #   ports:
  #     - '27100:27017'
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 3s
      retries: 3
